[2021-07-19 16:16:57] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:17:00] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 Command line code(1): include_once()
#1 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 Command line code(1): include_once()
#1 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:17:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:18:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:19:57] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:20:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:21:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:22:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:23:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:24:57] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:25:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:26:57] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:27:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:28:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:29:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:30:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:31:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:32:57] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:33:57] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:34:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:35:57] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:36:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:37:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:38:57] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:39:57] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:40:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:41:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-19 16:42:56] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
