[2021-07-20 07:36:54] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:34:19] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:34:19] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 Command line code(1): include_once()
#1 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 Command line code(1): include_once()
#1 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:34:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:35:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:36:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:37:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:38:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:39:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:40:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:41:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:42:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:43:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:44:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:45:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:46:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:47:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:48:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:49:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:50:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:51:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:52:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:53:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:54:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:55:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:56:06] prodcution.ERROR: Translation file [C:\xampp\htdocs\lerepass\resources\lang/en.json] contains an invalid JSON structure. {"exception":"[object] (RuntimeException(code: 0): Translation file [C:\\xampp\\htdocs\\lerepass\esources\\lang/en.json] contains an invalid JSON structure. at C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php:145)
[stacktrace]
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Traits\\EnumeratesValues.php(742): Illuminate\\Translation\\FileLoader->Illuminate\\Translation\\{closure}(Array, 'C:\\\\xampp\\\\htdocs...', 0)
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php(152): Illuminate\\Support\\Collection->reduce(Object(Closure), Array)
#2 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php(63): Illuminate\\Translation\\FileLoader->loadJsonPaths('en')
#3 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\Translator.php(279): Illuminate\\Translation\\FileLoader->load('en', '*', '*')
#4 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\Translator.php(109): Illuminate\\Translation\\Translator->load('*', '*', 'en')
#5 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\helpers.php(822): Illuminate\\Translation\\Translator->get('validation.reca...', Array, 'en')
#6 C:\\xampp\\htdocs\\lerepass\\vendor\\biscolab\\laravel-recaptcha\\src\\ReCaptchaServiceProvider.php(54): trans('validation.reca...')
#7 C:\\xampp\\htdocs\\lerepass\\vendor\\biscolab\\laravel-recaptcha\\src\\ReCaptchaServiceProvider.php(37): Biscolab\\ReCaptcha\\ReCaptchaServiceProvider->addValidationRule()
#8 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Biscolab\\ReCaptcha\\ReCaptchaServiceProvider->boot()
#9 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(914): Illuminate\\Container\\Container->call(Array)
#14 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(895): Illuminate\\Foundation\\Application->bootProvider(Object(Biscolab\\ReCaptcha\\ReCaptchaServiceProvider))
#15 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Biscolab\\ReCaptcha\\ReCaptchaServiceProvider), 22)
#16 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(896): array_walk(Array, Object(Closure))
#17 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#18 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#19 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#20 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#21 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"} 
[2021-07-20 17:56:06] prodcution.ERROR: Translation file [C:\xampp\htdocs\lerepass\resources\lang/en.json] contains an invalid JSON structure. {"exception":"[object] (RuntimeException(code: 0): Translation file [C:\\xampp\\htdocs\\lerepass\esources\\lang/en.json] contains an invalid JSON structure. at C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php:145)
[stacktrace]
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Traits\\EnumeratesValues.php(742): Illuminate\\Translation\\FileLoader->Illuminate\\Translation\\{closure}(Array, 'C:\\\\xampp\\\\htdocs...', 0)
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php(152): Illuminate\\Support\\Collection->reduce(Object(Closure), Array)
#2 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php(63): Illuminate\\Translation\\FileLoader->loadJsonPaths('en')
#3 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\Translator.php(279): Illuminate\\Translation\\FileLoader->load('en', '*', '*')
#4 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\Translator.php(109): Illuminate\\Translation\\Translator->load('*', '*', 'en')
#5 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\helpers.php(822): Illuminate\\Translation\\Translator->get('validation.reca...', Array, 'en')
#6 C:\\xampp\\htdocs\\lerepass\\vendor\\biscolab\\laravel-recaptcha\\src\\ReCaptchaServiceProvider.php(54): trans('validation.reca...')
#7 C:\\xampp\\htdocs\\lerepass\\vendor\\biscolab\\laravel-recaptcha\\src\\ReCaptchaServiceProvider.php(37): Biscolab\\ReCaptcha\\ReCaptchaServiceProvider->addValidationRule()
#8 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Biscolab\\ReCaptcha\\ReCaptchaServiceProvider->boot()
#9 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(914): Illuminate\\Container\\Container->call(Array)
#14 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(895): Illuminate\\Foundation\\Application->bootProvider(Object(Biscolab\\ReCaptcha\\ReCaptchaServiceProvider))
#15 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Biscolab\\ReCaptcha\\ReCaptchaServiceProvider), 22)
#16 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(896): array_walk(Array, Object(Closure))
#17 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#18 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#19 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#20 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#21 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"} 
[2021-07-20 17:56:06] prodcution.ERROR: Uncaught RuntimeException: Translation file [C:\xampp\htdocs\lerepass\resources\lang/en.json] contains an invalid JSON structure. in C:\xampp\htdocs\lerepass\vendor\laravel\framework\src\Illuminate\Translation\FileLoader.php:145
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\laravel\framework\src\Illuminate\Collections\Traits\EnumeratesValues.php(742): Illuminate\Translation\FileLoader->Illuminate\Translation\{closure}(Array, 'C:\\xampp\\htdocs...', 0)
#1 C:\xampp\htdocs\lerepass\vendor\laravel\framework\src\Illuminate\Translation\FileLoader.php(152): Illuminate\Support\Collection->reduce(Object(Closure), Array)
#2 C:\xampp\htdocs\lerepass\vendor\laravel\framework\src\Illuminate\Translation\FileLoader.php(63): Illuminate\Translation\FileLoader->loadJsonPaths('en')
#3 C:\xampp\htdocs\lerepass\vendor\laravel\framework\src\Illuminate\Translation\Translator.php(279): Illuminate\Translation\FileLoader->load('en', '*', '*')
#4 C:\xampp\htdocs\lerepass\vendor\laravel\framework\src\Illuminate\Translation\Translator. {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught RuntimeException: Translation file [C:\\xampp\\htdocs\\lerepass\esources\\lang/en.json] contains an invalid JSON structure. in C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php:145
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Traits\\EnumeratesValues.php(742): Illuminate\\Translation\\FileLoader->Illuminate\\Translation\\{closure}(Array, 'C:\\\\xampp\\\\htdocs...', 0)
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php(152): Illuminate\\Support\\Collection->reduce(Object(Closure), Array)
#2 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php(63): Illuminate\\Translation\\FileLoader->loadJsonPaths('en')
#3 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\Translator.php(279): Illuminate\\Translation\\FileLoader->load('en', '*', '*')
#4 C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\Translator. at C:\\xampp\\htdocs\\lerepass\\vendor\\laravel\\framework\\src\\Illuminate\\Translation\\FileLoader.php:145)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:56:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:57:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:58:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 17:59:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:00:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:01:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:02:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:03:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:04:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:05:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:06:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:07:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:08:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:09:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:10:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:11:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:12:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:13:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:14:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:15:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:16:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:17:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:18:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:19:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:20:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:21:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:22:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:23:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:24:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:25:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:26:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:27:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:28:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:29:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:30:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:31:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:32:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:33:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:34:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:35:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:36:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:37:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:38:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:39:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:40:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:41:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:42:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:43:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:44:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:45:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:46:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:47:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:48:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:49:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:50:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:51:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:52:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:53:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:54:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:55:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:56:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:57:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:58:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 18:59:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 19:00:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 19:01:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 19:02:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 19:03:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 19:04:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 19:05:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 19:06:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 19:07:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 19:08:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 19:09:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
[2021-07-20 19:10:31] prodcution.ERROR: Uncaught Error: Class 'Auth0\Login\Auth0User' not found in C:\xampp\htdocs\lerepass\app\Models\MyAuth0User.php:8
Stack trace:
#0 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(444): include()
#1 C:\xampp\htdocs\lerepass\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\Models\\MyAu...')
#4 Command line code(1): class_exists('App\\Models\\MyAu...')
#5 [internal function]: {closure}('App\\Models\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Auth0\\Login\\Auth0User' not found in C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8
Stack trace:
#0 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(444): include()
#1 C:\\xampp\\htdocs\\lerepass\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\xampp\\\\htdocs...')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Models\\\\MyAu...')
#3 [internal function]: spl_autoload_call('App\\\\Models\\\\MyAu...')
#4 Command line code(1): class_exists('App\\\\Models\\\\MyAu...')
#5 [internal function]: {closure}('App\\\\Models\\\\MyAu...')
#6 Command line code(1): array_filter(Array, Object(Closure))
#7 {main}
  thrown at C:\\xampp\\htdocs\\lerepass\\app\\Models\\MyAuth0User.php:8)
[stacktrace]
#0 {main}
"} 
